-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 08:31:02 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dietdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dietdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dietdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dietdb` ;

-- -----------------------------------------------------
-- Table `dietdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first` VARCHAR(255) NULL COMMENT '',
  `last` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `dob` DATE NULL COMMENT '',
  `gender` VARCHAR(255) NULL COMMENT '',
  `height` DECIMAL(10,0) NULL COMMENT '',
  `activity` VARCHAR(255) NULL COMMENT '',
  `calories_threshold` DECIMAL(10,0) NULL COMMENT '',
  `weight` DECIMAL(10,0) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietdb`.`meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietdb`.`meals` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `total_calories` DECIMAL(10,0) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  `calorie_deficit` DECIMAL(10,0) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_meals_users_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_meals_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `dietdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietdb`.`weight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietdb`.`weight` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `weight` DECIMAL(10,0) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_weight_users1_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_weight_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `dietdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietdb`.`meal_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietdb`.`meal_items` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `item` VARCHAR(255) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `meals_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_meal_items_meals1_idx` (`meals_id` ASC)  COMMENT '',
  CONSTRAINT `fk_meal_items_meals1`
    FOREIGN KEY (`meals_id`)
    REFERENCES `dietdb`.`meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
